import type { SidebarActionMessage, SidebarViewTab } from '@sidebar-protocol';

export const sidebarActions = {
  setTab: (value: SidebarViewTab): SidebarActionMessage => ({ type: 'ui.setTab', value }),
  refresh: (): SidebarActionMessage => ({ type: 'ui.refresh' }),
  globalBack: (): SidebarActionMessage => ({ type: 'nav.globalBack' }),
  globalForward: (): SidebarActionMessage => ({ type: 'nav.globalForward' }),
  toggleMetadataCollapse: (): SidebarActionMessage => ({ type: 'metadata.toggleCollapse' }),
  toggleMetadataEditing: (): SidebarActionMessage => ({ type: 'metadata.toggleEditing' }),
  addMetadataField: (): SidebarActionMessage => ({ type: 'metadata.addField' }),
  editMetadataField: (key: string): SidebarActionMessage => ({ type: 'metadata.editField', key }),
  removeMetadataField: (key: string): SidebarActionMessage => ({ type: 'metadata.removeField', key }),
  setMetadataStatus: (value: string): SidebarActionMessage => ({ type: 'metadata.setStatus', value }),
  addMetadataArrayItem: (key: string): SidebarActionMessage => ({ type: 'metadata.addArrayItem', key }),
  editMetadataArrayItem: (key: string, index: number): SidebarActionMessage => ({ type: 'metadata.editArrayItem', key, index }),
  removeMetadataArrayItem: (key: string, index: number): SidebarActionMessage => ({ type: 'metadata.removeArrayItem', key, index }),
  fillRequiredMetadata: (): SidebarActionMessage => ({ type: 'metadata.fillRequired' }),
  editImageFormat: (key: string): SidebarActionMessage => ({ type: 'images.editFormat', key }),
  resetImageToDefaults: (key: string): SidebarActionMessage => ({ type: 'images.resetToDefaults', key }),
  insertImage: (): SidebarActionMessage => ({ type: 'images.insertFromFilePicker' }),
  openPreview: (): SidebarActionMessage => ({ type: 'doc.openPreview' }),
  toggleFrontmatterFold: (): SidebarActionMessage => ({ type: 'doc.toggleFrontmatterFold' }),
  copyCleanText: (): SidebarActionMessage => ({ type: 'doc.copyCleanText' }),
  openHeadingLine: (line: number): SidebarActionMessage => ({ type: 'doc.openHeadingLine', line }),
  toggleTocBacklinks: (id: string): SidebarActionMessage => ({ type: 'doc.toggleTocBacklinks', id }),
  openBacklink: (filePath: string, line?: number): SidebarActionMessage => line === undefined
    ? ({ type: 'doc.openBacklink', filePath })
    : ({ type: 'doc.openBacklink', filePath, line }),
  openExternalLink: (url: string, basePath?: string): SidebarActionMessage => basePath
    ? ({ type: 'doc.openExternalLink', url, basePath })
    : ({ type: 'doc.openExternalLink', url }),
  openIdentifier: (id: string): SidebarActionMessage => ({ type: 'spine.openIdentifier', id }),
  openCategory: (key: string, prefix: string): SidebarActionMessage => ({ type: 'spine.openCategory', key, prefix }),
  spineHome: (): SidebarActionMessage => ({ type: 'spine.goHome' }),
  spineBack: (): SidebarActionMessage => ({ type: 'spine.goBack' }),
  spineForward: (): SidebarActionMessage => ({ type: 'spine.goForward' }),
  toggleSpineCollapse: (): SidebarActionMessage => ({ type: 'spine.toggleExplorerCollapse' }),
  toggleSpineBacklinks: (): SidebarActionMessage => ({ type: 'spine.toggleBacklinks' }),
  setBacklinkFilter: (value: string): SidebarActionMessage => ({ type: 'spine.setBacklinkFilter', value }),
  createSpineCategory: (): SidebarActionMessage => ({ type: 'spine.createCategory' }),
  pinActiveSpineEntry: (): SidebarActionMessage => ({ type: 'spine.pinActiveEntry' }),
  pinAllFromDocument: (): SidebarActionMessage => ({ type: 'spine.pinAllFromDocument' }),
  unpinEntry: (id: string): SidebarActionMessage => ({ type: 'spine.unpinEntry', id }),
  unpinAll: (): SidebarActionMessage => ({ type: 'spine.unpinAll' }),
  togglePinnedBacklinks: (id: string): SidebarActionMessage => ({ type: 'spine.togglePinnedBacklinks', id }),
  togglePinnedCollapse: (id: string): SidebarActionMessage => ({ type: 'spine.togglePinnedCollapse', id }),
  setPinnedBacklinkFilter: (id: string, value: string): SidebarActionMessage => ({ type: 'spine.setPinnedBacklinkFilter', id, value }),
  rebuildIndex: (): SidebarActionMessage => ({ type: 'spine.rebuildIndex' }),
  addComment: (): SidebarActionMessage => ({ type: 'comments.add' }),
  selectCommentThread: (id: string): SidebarActionMessage => ({ type: 'comments.selectThread', id }),
  replyComment: (id: string): SidebarActionMessage => ({ type: 'comments.reply', id }),
  toggleCommentResolved: (id: string, resolveThread?: boolean): SidebarActionMessage => resolveThread === undefined
    ? ({ type: 'comments.toggleResolved', id })
    : ({ type: 'comments.toggleResolved', id, resolveThread }),
  deleteComment: (id: string): SidebarActionMessage => ({ type: 'comments.delete', id }),
  jumpToComment: (id: string): SidebarActionMessage => ({ type: 'comments.jumpTo', id }),
  clearResolvedComments: (): SidebarActionMessage => ({ type: 'comments.clearResolved' }),
  runValidateCurrentFile: (): SidebarActionMessage => ({ type: 'workflow.validateCurrentFile' }),
  runCompile: (): SidebarActionMessage => ({ type: 'workflow.compile' }),
  runStageCheck: (): SidebarActionMessage => ({ type: 'workflow.stageCheck' }),
  runNewManuscript: (): SidebarActionMessage => ({ type: 'workflow.newManuscript' }),
  openOverviewFile: (filePath: string): SidebarActionMessage => ({ type: 'overview.openFile', filePath }),
  openFirstMissingMetadata: (filePath: string): SidebarActionMessage => ({ type: 'overview.openFirstMissingMetadata', filePath }),
  openFirstUnresolvedComment: (filePath: string, commentId: string): SidebarActionMessage => ({ type: 'overview.openFirstUnresolvedComment', filePath, commentId })
};
