name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Compile @stego-labs/shared
        run: npm run -w @stego-labs/shared compile

      - name: Compile stego-engine
        run: npm run -w @stego-labs/engine compile

      - name: Test stego-engine
        run: npm run -w @stego-labs/engine test

      - name: Compile stego-cli
        run: npm run -w @stego-labs/cli compile

      - name: Test stego-cli
        run: npm run -w @stego-labs/cli test

      - name: Compile stego-extension
        run: npm run -w packages/stego-extension compile

      - name: Test stego-extension
        run: npm run -w packages/stego-extension test
